# Generated by Django 2.2.6 on 2023-05-03 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('know_more', 'i want to know more'), ('sales', 'sales enquiry'), ('technical_fault', 'technical fault'), ('billing issue', 'billing issue'), ('other', 'other')], max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=20)),
                ('to', models.CharField(choices=[('contact_center', 'contact_center'), ('markerting', 'markerting'), ('sales', 'sales'), ('management', 'management'), ('field_service', 'field service')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crmapp.Persona')),
                ('staff_roles', models.CharField(choices=[('contact_center', 'contact_center'), ('markerting', 'markerting'), ('sales', 'sales'), ('management', 'management'), ('field_service', 'field service')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('crmapp.persona',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crmapp.Persona')),
            ],
            bases=('crmapp.persona',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('read', 'read'), ('replied', 'replied')], max_length=50)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Conversation')),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_from', to='crmapp.Persona')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_to', to='crmapp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Conversation')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversations', models.ManyToManyField(to='crmapp.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Customer'),
        ),
    ]
