# Generated by Django 2.2.6 on 2023-05-06 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('contact_center', 'contact_center'), ('markerting', 'markerting'), ('sales', 'sales'), ('management', 'management'), ('field_service', 'field service')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='agent',
        ),
        migrations.AddField(
            model_name='conversation',
            name='agents',
            field=models.ManyToManyField(to='crmapp.Agent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('first_contact', 'first_contact'), ('multiple_contact', 'multiple_contact'), ('lead', 'lead'), ('purchased', 'purchased'), ('unsubscribed', 'unsubscribed')], default='first contact', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crmapp.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='intrests',
            field=models.ManyToManyField(to='crmapp.Intrest'),
        ),
    ]
