# Generated by Django 2.2.6 on 2023-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20230506_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('open', 'open'), ('closed', 'closed'), ('escalated', 'escalated')], default='unread', max_length=50),
            preserve_default=False,
        ),
    ]
