# Generated by Django 2.2.6 on 2023-05-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
