# Generated by Django 2.2.6 on 2023-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_auto_20230507_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.CharField(default='shghs', max_length=200),
            preserve_default=False,
        ),
    ]
