# Generated by Django 2.2.6 on 2023-05-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
