# Generated by Django 2.2.6 on 2023-05-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_auto_20230507_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.CharField(default='hdhdhd', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('first_contact', 'first contact'), ('multiple_contact', 'multiple contact'), ('lead', 'lead'), ('purchased', 'purchased'), ('unsubscribed', 'unsubscribed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Agent'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Department')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crmapp.Product'),
            preserve_default=False,
        ),
    ]
