# Generated by Django 2.2.6 on 2023-05-07 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_auto_20230507_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crmapp.Department'),
            preserve_default=False,
        ),
    ]
