# Generated by Django 2.2.6 on 2023-05-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_notification_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
        migrations.AddField(
            model_name='notification',
            name='agents',
            field=models.ManyToManyField(to='crmapp.Agent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='departments',
            field=models.ManyToManyField(to='crmapp.Department'),
        ),
    ]
