# Generated by Django 2.2.6 on 2023-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_auto_20230507_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('in_progress', 'in progress'), ('done', 'done')], default='in_progress', max_length=20),
            preserve_default=False,
        ),
    ]
