# Generated by Django 2.2.6 on 2023-05-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_ticket_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ManyToManyField(to='crmapp.Department'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
