# Generated by Django 2.2.6 on 2023-05-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_auto_20230508_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='crmapp.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.CharField(default='please do this job', max_length=100),
            preserve_default=False,
        ),
    ]
