# Generated by Django 2.2.6 on 2023-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_auto_20230508_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='intrested_in',
            field=models.ManyToManyField(to='crmapp.Product'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('prospect', 'prospect'), ('qualified_lead', 'qualified_lead'), ('pitch', 'pitch'), ('objection_handling', 'objection_handling'), ('nurturing', 'nurturing')], default='prospect', max_length=30),
            preserve_default=False,
        ),
    ]
